
spring:
  application:
    name: strategy-engine
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: strategy-engine
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: org.pm.common.model.Tick
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

topics:
  market: market-ticks
  signals: trade-signals

# server port (optional)
server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    org.pm.strategyengine: DEBUG

